# -*- coding: utf-8 -*-
"""运行时 JS 生成。"""

from __future__ import annotations

import json
import os
from datetime import datetime
from typing import Dict, Optional, Sequence

from .constants import (
    RUNTIME_PROTECTED_EXACT_TEXTS,
    TOOL_NAME,
    TOOL_VERSION,
)

_TEMPLATE_PATH = os.path.join(os.path.dirname(__file__), "runtime_template.js")


def load_runtime_template() -> str:
    with open(_TEMPLATE_PATH, "r", encoding="utf-8") as handle:
        return handle.read()


def generate_js_code(
    translation_dictionary_data: Dict[str, str],
    *,
    manifest_id: str = "dry-run",
    protected_exact_texts: Optional[Sequence[str]] = None,
    tool_version: str = TOOL_VERSION,
) -> str:
    """生成包含词典与运行时逻辑的 cursor_hanhua.js。"""
    protected = list(protected_exact_texts or RUNTIME_PROTECTED_EXACT_TEXTS)
    template = load_runtime_template()
    rendered = (
        template
        .replace("__TOOL_NAME__", json.dumps(TOOL_NAME, ensure_ascii=False))
        .replace("__TOOL_VERSION__", json.dumps(tool_version, ensure_ascii=False))
        .replace("__MANIFEST_ID__", json.dumps(manifest_id, ensure_ascii=False))
        .replace(
            "__TRANSLATION_DICTIONARY__",
            json.dumps(translation_dictionary_data, ensure_ascii=False),
        )
        .replace(
            "__PROTECTED_EXACT_TEXTS__",
            json.dumps(protected, ensure_ascii=False),
        )
    )
    header = (
        f"/* Generated by {TOOL_NAME} v{tool_version} at "
        f"{datetime.now().strftime('%Y-%m-%d %H:%M:%S')} manifest={manifest_id} */\n"
    )
    return header + rendered


def build_injection_block(manifest_id: str, tool_version: str = TOOL_VERSION) -> str:
    from .constants import INJECTION_BEGIN, INJECTION_END, INJECTION_MARKER, TRANSLATION_JS_NAME

    return (
        f"\n\t{INJECTION_MARKER}\n"
        f"\t{INJECTION_BEGIN} tool={TOOL_NAME} version={tool_version} "
        f"manifest={manifest_id} -->\n"
        f'\t<script src="./{TRANSLATION_JS_NAME}"></script>\n'
        f"\t{INJECTION_END}\n"
    )
